name: Create Sentry release

on:
  push:
    branches:
      - main

jobs:
  create_sentry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Create a Sentry.io release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: hassan-abouelela
          SENTRY_PROJECT: eval-bot
        with:
          environment: production
          version_prefix: bot@
